services:
  - type: web
    name: rageclicker
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --workers 1 --threads 2 --timeout 60
    envVars:
      - key: TURSO_URL
        sync: false
      - key: TURSO_TOKEN
        sync: false
      - key: PYTHON_VERSION
        value: 3.11.0